### ISSUE TITLE
Distro: Segmentation fault (Core dumped)

### ISSUE THREAD

**Issue by ghost** [kernaltrap8/tinyfetch#1]
I think it segfaults when trying to parse /etc/os-release. on my system /etc/os-release is a symlink to /usr/host/lib/os-release where /usr/host is a symlink to /usr/x86_64-pc-linux-gnu

**Comment by kernaltrap8** [comment]
This should be fixed with commit [1f470f8](https://github.com/kernaltrap8/tinyfetch/commit/1f470f8f12aedad7660e002312bce5ed615fdde5)
