### ISSUE TITLE
Latest tinyfetch shows current CPU frequency instead of base clock

### ISSUE THREAD

**Issue by HyperWinX** [kernaltrap8/tinyfetch#2]
Instead of showing base CPU frequency, tinyfetch shows current CPU frequency. For example, my current frequency is 1.4GHz, when base clock is 4GHz. Would like to see fix for that.
![image](https://github.com/user-attachments/assets/78b654cd-4f3d-4242-b59e-b6a0e6fa4574)

**Comment by kernaltrap8** [comment]
Unfortunately there is a minor limitation with how I am getting the clock speed. Reading it from /proc/cpuinfo only allows me to get the current clock speed, and not the base frequency. I dont think I would be able to get the base freq without needing a external library.

**Comment by HyperWinX** [comment]
Thanks for reply, closing issue. If i'll find how to do that, i'll ping.

**Comment by HyperWinX** [comment]
Also yeah, please fix this quote at the start of distro name.

**Comment by kernaltrap8** [comment]
I noticed that, I'll work on it when I can.
